development:
  adapter: postgresql
  encoding: unicode
  database: volunteer_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: volunteer_test
  pool: 5

cucumber:
  <<: *test
